### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by ibby89va** [erlwes/InactiveWipe#2]
![image](https://github.com/user-attachments/assets/4562dad2-e228-4534-bef8-5676ad085f61)

Hello, I have a problem to run a script,  it appear this error. The script doesn't find the user and there is this error: Line |
  76 |      [int]$Script:disabledPercentage = ($DisabledCount / $totalCount)  …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to divide by zero. 

![image](https://github.com/user-attachments/assets/bb3822e1-b060-459f-b5b5-6c809978c8d5)

can you help me?

**Comment by erlwes** [comment]
Try now. The correct errormessage should be included now for the failing rest-method (typo in script).

Also there is no need to continue script if auth og query fails. Divide by zero is caused because there are 0 users. So the script now exits if the auth or graph query fails, as there is no need to continue.

The divide by zero fail would happen if it actually is 0 disabled users too, so I should fix this aswell, bu I have not done that, yet.

Please re-download and run again.

**Comment by ibby89va** [comment]
thanks, I had to add the AuditLog.Read.All and now it works correctly

**Comment by erlwes** [comment]
That surprised me, but it seems that if you request "SignInActivity"-property the graph request requires this permission.
Thanks for letting me know. Glad it works now :)
